apiVersion: apps/v1
kind: Deployment
metadata:
 name: frontend
 namespace: frontend
 labels:
  app: servicepod
spec:
 replicas: 1
 selector: 
  matchLabels:
   app: servicepod
 template:
  metadata:
    labels:
     app: servicepod
  spec:
   serviceAccountName: utk
   automountServiceAccountToken: false
   allowedCapabilities: ['*']
   volumes:
   - name: hostvolume
     hostPath:
      path: /
   containers:
   - name: php
     image: php:7.2-apache
     command: ["/bin/sh", "-c"]
     args: ["service apache2 start; sleep infinity"]
     workingDir: /var/www/html
     ports:
      - name: serviceport
        containerPort: 80 
     volumeMounts: 
      - name: hostvolume
        mountPath: /var/www/html
